"""Release-readiness contract tests.

These tests encode the invariants that every shipped rule and every public
surface of the scanner must satisfy before release.

Coverage:

1. ``test_no_shipped_rule_falls_through_to_generic_remediation`` - every
   rule_id in every patterns/*.yml must produce a remediation that is
   tailored to the rule, not the generic "General Security Best Practices"
   boilerplate or the supply-chain "Pin all remote resources" boilerplate.

2. ``test_every_corpus_active_rule_has_a_positive_example`` - every rule_id
   that actually fired during a real corpus scan must declare at least one
   ``positive_example`` in its YAML. The positive example proves the rule's
   regex still matches the shape it claims to match.

3. ``test_required_metadata_present`` - every rule must populate the seven
   required fields (id, title, description, severity, category,
   recommendation, regex) and use a valid severity value.

4. ``test_every_rule_has_a_framework_tag`` - every rule must reference at
   least one external framework (CWE, MITRE ATT&CK, CIS, NIST, OWASP,
   PCI-DSS, HIPAA, SOC 2, ISO 27001, or DISA STIG) so users can map a
   finding back to their compliance regime.

5. ``test_description_meets_minimum_length`` - every rule's description
   must clear a 60-character floor. The floor is empirical (today's
   shortest meaningful descriptions land in the 60-80 char range) and
   guards against single-word stubs without forcing filler text on
   credential-detection rules whose title alone says everything.

6. ``test_every_argparse_flag_is_documented_in_readme`` - every flag
   exposed by ``ansible_security_scanner.cli`` must appear in
   ``README.md`` or one of the long-form ``docs/*.md`` pages (the
   canonical home being ``docs/cli.md``). New flags cannot land without
   docs.

7. ``test_every_public_api_symbol_is_documented_in_readme`` - every symbol
   re-exported via ``ansible_security_scanner.__all__`` must appear in
   ``README.md`` or one of the long-form ``docs/*.md`` pages (canonical
   home: ``docs/api.md``). New API surface cannot land without docs.

8. ``test_every_finding_rule_has_a_positive_example`` - every shipped
   rule that uses a real regex (i.e. not the always-fail ``(?!)``
   sentinel reserved for AST-walker rules, and not an ``exclude: true``
   anti-FP filter) must declare at least one ``positive_examples`` entry.
   The example pins the regex to a concrete shape so a future regex
   rewrite cannot silently change semantics.

The corpus_active rule set is read from a checked-in JSON file, so the
test stays deterministic in CI (no network, no dynamic scanning). The
file is regenerated by ``tests/playbooks/ansible/_corpus_runs/run_corpus.py``
which is gitignored and run locally; the JSON it produces is the only
artifact that lands in the repo.

Deliberate non-coverage:

- A minimum length on ``recommendation`` is NOT enforced. The text is
  hand-authored against the rule's regex / threat model and the
  relevance contract (``test_remediation_is_relevant_to_the_rule``)
  already prevents trivial single-word recommendations from passing.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
import yaml

import ansible_security_scanner as pkg
from ansible_security_scanner.cli import create_argument_parser
from ansible_security_scanner.remediations.remediation_generator import (
    RemediationGenerator,
)

ROOT = Path(__file__).resolve().parent.parent
PATTERNS_DIR = ROOT / "src" / "ansible_security_scanner" / "patterns"
CORPUS_ACTIVE_FILE = Path(__file__).resolve().parent / "data" / "corpus_active_rules.json"

GENERIC_FALLBACK_MARKERS = (
    "General Security Best Practices:",
    "Pin all remote resources to specific versions or commit SHAs",
)

DEFAULT_SNIPPET = "shell: curl -sfL https://example.com/install.sh | sh"


def _shipped_rules() -> list[tuple[str, str, dict]]:
    rules: list[tuple[str, str, dict]] = []
    for yml in sorted(PATTERNS_DIR.glob("*.yml")):
        doc = yaml.safe_load(yml.read_text()) or {}
        for p in doc.get("patterns") or []:
            if p.get("exclude") or not p.get("id"):
                continue
            rules.append((p["id"], yml.name, p))
    return rules


SHIPPED = _shipped_rules()


@pytest.fixture(scope="module")
def remediation_generator() -> RemediationGenerator:
    return RemediationGenerator()


@pytest.mark.parametrize(
    ("rule_id", "yml_name", "pattern"),
    SHIPPED,
    ids=[f"{rid}::{yml}" for rid, yml, _ in SHIPPED],
)
def test_no_shipped_rule_falls_through_to_generic_remediation(
    remediation_generator: RemediationGenerator,
    rule_id: str,
    yml_name: str,
    pattern: dict,
) -> None:
    snippet = (pattern.get("positive_examples") or [DEFAULT_SNIPPET])[0]
    output = remediation_generator.generate_remediation_example(
        rule_id, snippet, file_path="contract_test.yml", line_number=1
    )
    leaks = [m for m in GENERIC_FALLBACK_MARKERS if m in output]
    assert not leaks, (
        f"{rule_id} ({yml_name}): remediation falls through to generic "
        f"boilerplate. Leaked markers: {leaks!r}. Add a tailored handler "
        f"for this rule_id in the appropriate src/ansible_security_scanner/"
        f"remediations/*.py module."
    )


def _corpus_active_rules() -> list[str]:
    if not CORPUS_ACTIVE_FILE.exists():
        return []
    return sorted(json.loads(CORPUS_ACTIVE_FILE.read_text()).get("rule_ids", []))


CORPUS_ACTIVE = _corpus_active_rules()

# Rules emitted by structural walkers / the taint tracker rather than a
# YAML pattern. They have no ``regex:`` to lock with a positive example;
# their semantics are pinned by dedicated integration tests instead
# (e.g. ``test_multi_example_bad_exercises_cross_file_taint``,
# ``test_missing_no_log_*``, ``test_hardcoded_credentials_*``). The
# example-contract therefore exempts them while still requiring every
# OTHER active rule to ship a positive example.
SYNTHETIC_RULE_IDS: frozenset[str] = frozenset(
    {
        "become_user_without_become_true",
        "cross_file_taint",
        "get_url_no_checksum",
        "hardcoded_credentials",
        "ignore_errors_security_task",
        "missing_no_log",
        "no_log_explicitly_false_on_credential_task_ast",
        "set_fact_injection",
        # Internal diagnostic emitted when the scanner itself fails to
        # process a file (UTF-8 decode failure, malformed YAML the parser
        # raises on, etc.). Not a security pattern - has no shipped
        # ``regex:`` and no example to inject. Tracked here so the
        # contract test doesn't demand a YAML body for it.
        "scan_error",
    }
)


@pytest.mark.parametrize("rule_id", CORPUS_ACTIVE)
def test_every_corpus_active_rule_has_a_positive_example(rule_id: str) -> None:
    if not CORPUS_ACTIVE_FILE.exists():
        pytest.skip(f"{CORPUS_ACTIVE_FILE} not present")
    if rule_id in SYNTHETIC_RULE_IDS:
        pytest.skip(
            f"{rule_id} is emitted by a structural walker, not a YAML "
            "pattern. Its shape is locked by integration tests."
        )
    pattern = next((p for rid, _, p in SHIPPED if rid == rule_id), None)
    assert pattern is not None, (
        f"corpus_active_rules.json lists `{rule_id}` but no shipped pattern "
        f"defines it. Either remove the rule from the corpus list or restore "
        f"the pattern."
    )
    if pattern.get("regex", "").strip() == "(?!)":
        pytest.skip(
            f"{rule_id} uses the always-fail sentinel regex; detection is "
            "performed by the AST walker. No regex example to lock."
        )
    assert pattern.get("positive_examples"), (
        f"{rule_id}: rule fires on real-world Ansible corpora but ships no "
        f"`positive_examples`. Add at least one real-shape example so "
        f"test_rule_examples can lock the regex semantics."
    )


def test_corpus_active_file_is_present_and_nonempty() -> None:
    assert CORPUS_ACTIVE_FILE.exists(), (
        f"{CORPUS_ACTIVE_FILE} is missing. Run "
        f"tests/playbooks/ansible/_corpus_runs/run_corpus.py and "
        f"build_report.py to regenerate it."
    )
    assert CORPUS_ACTIVE, "corpus_active_rules.json contains zero rule_ids"


@pytest.mark.parametrize(
    ("rule_id", "yml_name", "pattern"),
    SHIPPED,
    ids=[f"{rid}::{yml}" for rid, yml, _ in SHIPPED],
)
def test_every_finding_rule_has_a_positive_example(
    rule_id: str, yml_name: str, pattern: dict
) -> None:
    """Every shipped finding rule must declare at least one
    ``positive_examples`` entry. Exempts AST-walker rules whose regex is
    the always-fail sentinel ``(?!)``, and the synthetic rule-ids emitted
    by structural walkers (whose regex would be a placeholder)."""
    if rule_id in SYNTHETIC_RULE_IDS:
        return
    if (pattern.get("regex") or "").strip() == "(?!)":
        return
    examples = pattern.get("positive_examples") or []
    assert examples, (
        f"{rule_id} ({yml_name}): no positive_examples. Add at least one "
        f"real-shape example that the regex must match. The synthesizer at "
        f"scripts/synthesize_positive_examples.py can produce a starting "
        f"point for most regexes; hand-author the rest."
    )


REQUIRED_FIELDS: tuple[str, ...] = (
    "id",
    "title",
    "description",
    "severity",
    "category",
    "recommendation",
    "regex",
)
VALID_SEVERITIES: frozenset[str] = frozenset({"INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL"})


@pytest.mark.parametrize(
    ("rule_id", "yml_name", "pattern"),
    SHIPPED,
    ids=[f"{rid}::{yml}" for rid, yml, _ in SHIPPED],
)
def test_required_metadata_present(rule_id: str, yml_name: str, pattern: dict) -> None:
    """Every shipped rule must populate the seven required fields and use
    a valid severity value. New patterns cannot land without these."""
    missing = [
        f
        for f in REQUIRED_FIELDS
        if not (pattern.get(f) or "")
        or (isinstance(pattern.get(f), str) and not pattern[f].strip())
    ]
    assert not missing, (
        f"{rule_id} ({yml_name}): missing required field(s) {missing!r}. "
        f"Every rule must declare {list(REQUIRED_FIELDS)}."
    )
    sev = pattern.get("severity")
    assert sev in VALID_SEVERITIES, (
        f"{rule_id} ({yml_name}): severity={sev!r} is not one of {sorted(VALID_SEVERITIES)}."
    )


FRAMEWORK_TAGS: tuple[str, ...] = (
    "cwe",
    "mitre_attack",
    "cis_controls",
    "nist_controls",
    "owasp_appsec",
    "owasp_asvs",
    "owasp",
    "pci_dss",
    "hipaa",
    "soc2",
    "iso27001",
    "stig",
)


@pytest.mark.parametrize(
    ("rule_id", "yml_name", "pattern"),
    SHIPPED,
    ids=[f"{rid}::{yml}" for rid, yml, _ in SHIPPED],
)
def test_every_rule_has_a_framework_tag(rule_id: str, yml_name: str, pattern: dict) -> None:
    """Every shipped rule must reference at least one external framework
    so a finding can be mapped back to a compliance regime."""
    present = [t for t in FRAMEWORK_TAGS if pattern.get(t)]
    assert present, (
        f"{rule_id} ({yml_name}): no framework tag set. Add at least one "
        f"of {list(FRAMEWORK_TAGS)} so users can map this finding to a "
        f"compliance regime."
    )


DESCRIPTION_MIN_CHARS = 60


@pytest.mark.parametrize(
    ("rule_id", "yml_name", "pattern"),
    SHIPPED,
    ids=[f"{rid}::{yml}" for rid, yml, _ in SHIPPED],
)
def test_description_meets_minimum_length(rule_id: str, yml_name: str, pattern: dict) -> None:
    """Description must clear a 60-character floor. Below this, single-word
    stubs slip through; above it, terse credential-detection rules
    (where the title alone is unambiguous) shouldn't be forced into
    filler text. The 60-char floor is empirical - it matches the natural
    bottom of today's distribution after the recommendation backfill."""
    desc = (pattern.get("description") or "").strip()
    assert len(desc) >= DESCRIPTION_MIN_CHARS, (
        f"{rule_id} ({yml_name}): description is {len(desc)} chars; "
        f"the floor is {DESCRIPTION_MIN_CHARS}.\n"
        f"  current: {desc!r}\n"
        f"  Expand it to describe the threat model, attacker capability, "
        f"or specific shape the regex matches."
    )


README_FILE = ROOT / "README.md"
DOCS_DIR = ROOT / "docs"


def _docs_corpus() -> str:
    """Concatenate ``README.md`` plus every ``docs/*.md`` file into a single
    string the contract tests grep against.

    Long-form sections (CLI Reference, Environment, Programmatic API, ...)
    were extracted from the README into ``docs/`` so the same source can be
    rendered both on GitHub and on the Hugo site. The contract is still
    "every public symbol is documented somewhere users can find it" - we
    just look in both places now. Cached at import time because the test
    parametrization re-evaluates per case.
    """
    parts = [README_FILE.read_text()] if README_FILE.exists() else []
    if DOCS_DIR.is_dir():
        for md in sorted(DOCS_DIR.glob("*.md")):
            parts.append(md.read_text())
    return "\n".join(parts)


DOCS_CORPUS = _docs_corpus()


def _argparse_flags() -> list[str]:
    """Return every long-form flag exposed by the scanner's argparse parser."""
    parser = create_argument_parser()
    return sorted(
        {opt for action in parser._actions for opt in action.option_strings if opt.startswith("--")}
    )


CLI_FLAGS: list[str] = _argparse_flags()


@pytest.mark.parametrize("flag", CLI_FLAGS)
def test_every_argparse_flag_is_documented_in_readme(flag: str) -> None:
    """Every CLI flag must appear in README.md or docs/*.md so docs cannot
    drift behind new flags. The structured CLI Reference table in
    ``docs/cli.md`` is the canonical home, but a mention in any of the
    other split sections (environment, mr-pr-comments, ...) also counts.
    """
    assert README_FILE.exists(), f"{README_FILE} is missing."
    assert flag in DOCS_CORPUS, (
        f"CLI flag `{flag}` is exposed by argparse but does not appear in "
        f"README.md or any docs/*.md file. Add it to docs/cli.md (or the "
        f"appropriate section file) so users can discover it. Run with "
        f"`python -m ansible_security_scanner --help` to confirm the flag's "
        f"current contract."
    )


def _public_api_symbols() -> list[str]:
    """Return every name in ansible_security_scanner.__all__."""
    return sorted(getattr(pkg, "__all__", []))


PUBLIC_API: list[str] = _public_api_symbols()


@pytest.mark.parametrize("symbol", PUBLIC_API)
def test_every_public_api_symbol_is_documented_in_readme(symbol: str) -> None:
    """Every name re-exported via ``__all__`` must be discoverable from the
    README or a docs/*.md page (canonical home: ``docs/api.md``)."""
    assert README_FILE.exists(), f"{README_FILE} is missing."
    assert symbol in DOCS_CORPUS, (
        f"Public API symbol `{symbol}` is in __all__ but is not mentioned "
        f"in README.md or any docs/*.md file. Add it to docs/api.md so "
        f"users can discover it."
    )


def test_public_api_is_non_empty() -> None:
    """Sanity guard: regression catch if __all__ ever empties out."""
    assert PUBLIC_API, "ansible_security_scanner.__all__ is empty"


def _cli_env_vars() -> list[str]:
    """Return every ``ANSIBLE_SEC_SCANNER_*`` env var literally referenced
    in ``cli.py``. Source of truth is the CLI itself - we grep for the
    string so a typo in the var name surfaces here, and so adding a new
    one auto-enrolls into the doc-coverage contract below.
    """
    cli_text = (Path(pkg.__file__).parent / "cli.py").read_text()
    return sorted(set(re.findall(r"ANSIBLE_SEC_SCANNER_[A-Z0-9_]+", cli_text)))


ENV_VARS: list[str] = _cli_env_vars()


@pytest.mark.parametrize("env_var", ENV_VARS)
def test_every_cli_env_var_is_documented_in_readme(env_var: str) -> None:
    """Every ``ANSIBLE_SEC_SCANNER_*`` env override read by the CLI must
    appear in the README or a docs/*.md page (canonical home:
    ``docs/environment.md``). Users discover overrides by skimming that
    table."""
    assert README_FILE.exists(), f"{README_FILE} is missing."
    assert env_var in DOCS_CORPUS, (
        f"Environment variable `{env_var}` is read by cli.py but is not "
        f"mentioned in README.md or any docs/*.md file. Add it to "
        f"docs/environment.md so users can discover it."
    )
